### PR TITLE
resolve conflict errors

### PR DESCRIPTION
**Pull request by gotcha**
happening when storage is changed by concurrent scale requests

### CODE REVIEW

**Comment by gforcada** [comment]
Tests running: http://jenkins.plone.org/job/pull-request-5.0/594

**Comment by do3cc** [comment]
Cool.
While in theory everybody should know this, most probably don't so maybe you add a note in the upgrade that it is important to also have the new version of this package in the zeo server. Because sometimes conflict resolution happens in zeoserver

**Comment by jensens** [comment]
great, just a short changelog entry is missing

**Comment by gotcha** [comment]
I added the changelog.
I'll merge as soon as I see that the broken `plone.namedfile` tests pass.

**Pull request merged**
