### PR TITLE
Python3 cleanup + tox + GHA

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/plone/plone.scale/issues/44, except my idea for registering AnnotationStorage as an adapter, which we want to do in `plone.namedfile` instead.

I have created branch 3.x before this, which is for coredev 5.2.

On GHA I want to keep testing master with the 5.2 versions, but only on Python 3.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Any reviewers?

So really hurry for this one. But once this is merged, I could have a go at removing the [deprecated passing of a factory](https://github.com/plone/plone.scale/blob/e61aec4c2db7943f231b9c3ad8b110682abb8027/plone/scale/storage.py#L185-L187) to the AnnotationStorage.

**Comment by yurj** [comment]
> Any reviewers?
> 
> So really hurry for this one. But once this is merged, I could have a go at removing the [deprecated passing of a factory](https://github.com/plone/plone.scale/blob/e61aec4c2db7943f231b9c3ad8b110682abb8027/plone/scale/storage.py#L185-L187) to the AnnotationStorage.

can you highlight the core changes? I can see only reformatting and python3/package updating...

**Comment by mauritsvanrees** [comment]
> can you highlight the core changes? I can see only reformatting and python3/package updating...

- Python 3 only
- tox and GitHub Actions for Plone 5.2 and 6.0 on Py 3
- Removed sphinx-generated docs, which were outdated, and the relevant parts were already in the readme.

**Pull request merged**
