### PR TITLE
refactor storage

### PR DESCRIPTION
**Pull request by gotcha**
before enabling resolution of ConflictErrors

### CODE REVIEW

**Comment by gforcada** [comment]
Tests running: http://jenkins.plone.org/job/pull-request-5.0/593/

**Comment by gotcha** [comment]
https://community.plone.org/t/unstable-plone-namedfile-tests/1250

**Comment by gforcada** [comment]
@gotcha jenkins reports about two (expected?) test failures, could you take a look at them?

**Comment by gforcada** [comment]
btw. the other pull request is related (so they need to be applied both at the same time or are isolated from each  other?)

In Jenkins pull request jobs you can put as many pull requests as you want (one per line)

**Comment by jensens** [comment]
- changelog entry is missing
- @gotcha whats the state here?

**Comment by gotcha** [comment]
I need to fix the plone.namedfile tests.

**Comment by gotcha** [comment]
Merged with https://github.com/plone/plone.scale/pull/7

**Pull request closed without merging**
