### PR TITLE
New ``mode`` argument replacing ``direction``

### PR DESCRIPTION
**Pull request by fschulze**
As suggested by @thet, this PR implements the new ``mode`` argument replacing the now deprecated ``direction`` argument. Both the names suggested by @thet and @davisagli are supported.

### CODE REVIEW

**Comment by fschulze** [comment]
I have no clue why ``testDeprecations`` fails in jenkins, but not locally.

The remaining failures seem to be unrelated flaky tests.

**Comment by thet** [comment]
thanks for the PR!

I re-run the tests to see if the failures were of some flaky nature.

there are some methods named ``_thumbnail`` and ``thumbnail``, which could also be renamed, but then deprecated using ``zope.deprecation``. But I don't see this as part of this PR.

**Comment by fschulze** [comment]
If I see it correctly, then those are from PIL, not plone.scale. And _scale_thumbnail is named after the used method from PIL. Or do you mean something else?

**Comment by thet** [comment]
no I mean those. thanx for clarifying!

**Comment by fschulze** [comment]
So, only the deprecation warning test fails. Should we remove it? Or do you have an idea why it fails? It works when running only the plone.scale tests.

**Comment by fschulze** [comment]
I'm at the Plone Conference till friday if someone would like to look at this with me

**Comment by fschulze** [comment]
@thet ping

**Comment by jensens** [comment]
Hmm, @fschulze whats the state here?

**Comment by fschulze** [comment]
The state is that the test for the deprecation warning works locally, but fails with jenkins. The question is if I should just remove it to get it green. The rest is working fine on our end and all the other tests pass.

**Comment by fschulze** [comment]
I've updated this PR to the current code base and the 1 failure for Plone 5.1 seems to be an unrelated flaky test.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@fschulze first of all: THANK YOU for this PR and SORRY for not continuing on it earlier. I was the one who requested further changes but did not follow up :(

However, I sort of changed my mind regarding the deprecations. I openened a new PR based on yours with an additional commit fixing that.
If everybody feels that the new PR is the wrong approach we can still open up this one again.

But for now, I'm closing this in favor of that: https://github.com/plone/plone.scale/pull/36

**Pull request closed without merging**
