### PR TITLE
ask for original image if info["data"] is not set

### PR DESCRIPTION
**Pull request by MrTango**
This needs this commit, which i accidentally directly committed to master here: 
https://github.com/plone/plone.namedfile/commit/04fad1206fa570d9ed931915ac838c2cf7248680

### CODE REVIEW

**Comment by MrTango** [comment]
@jenkins-plone-org please run jobs

**Comment by MrTango** [comment]
With this changes, we return the original image data and store it in the annotation, so that this will not get triggered for every request again, if the image does not have a scale.
Fixes: https://github.com/plone/Products.CMFPlone/issues/3678

**Comment by MrTango** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
This uses the original image for all scales.
I think this PR can be replaced with https://github.com/plone/plone.namedfile/pull/136

**Pull request closed without merging**
